CREATE OR REPLACE PROCEDURE PUBLIC."DELETE_ACCOUNT"(
    IN P_USER_ID BIGINT,
    OUT SUCCESS BOOLEAN
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_AUDIT_ID BIGINT;
BEGIN
    SELECT "AUDIT_ID" INTO V_AUDIT_ID
    FROM PUBLIC."USER"
    WHERE "USER_ID" = P_USER_ID;

    IF V_AUDIT_ID IS NULL THEN
        SUCCESS := FALSE;
        RETURN;
    END IF;

    DELETE FROM PUBLIC."USER"
    WHERE "USER_ID" = P_USER_ID;

    DELETE FROM PUBLIC."AUDIT"
    WHERE "AUDIT_ID" = V_AUDIT_ID;

    SUCCESS := TRUE;
END;
$$;

ALTER PROCEDURE PUBLIC."DELETE_ACCOUNT"(BIGINT, BOOLEAN)
OWNER TO POSTGRES;
