CREATE OR REPLACE PROCEDURE "GET_ACCOUNT" (
    OUT DATA JSON,
    IN P_USER_ID BIGINT DEFAULT NULL,
    IN P_EMAIL TEXT DEFAULT NULL,
    IN P_USERNAME TEXT DEFAULT NULL,
    IN P_STATUS BIGINT DEFAULT NULL,
    IN P_MEMBERSHIP_PLAN_ID BIGINT DEFAULT NULL,
    IN P_PAGE INT DEFAULT 1,
    IN P_LIMIT INT DEFAULT 10
)
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT
            "USER"."USER_ID",
            "USER"."AUDIT_ID",
            "USER"."EMAIL",
            "USER"."USERNAME",
            "USER"."HASHED_PASSWORD",
            "USER"."AVATAR_URL",
            "USER"."STATUS",
            "MEMBERSHIP_PLAN"."MEMBERSHIPPLAN_ID",
            "MEMBERSHIP_PLAN"."NAME" AS "MEMBERSHIP_PLAN_NAME",
            "MEMBERSHIP_PLAN"."DESCRIPTION" AS "MEMBERSHIP_PLAN_DESCRIPTION",
            "MEMBERSHIP_PLAN"."AMOUNT" AS "MEMBERSHIP_PLAN_AMOUNT",
            "AUDIT"."CREATED_AT" AS "USER_CREATED_AT",
            "AUDIT"."UPDATED_AT" AS "USER_UPDATED_AT"
        FROM
            PUBLIC."USER"
            LEFT JOIN PUBLIC."MEMBERSHIP_PLAN" 
                ON "MEMBERSHIP_PLAN"."MEMBERSHIPPLAN_ID" = "USER"."MEMBERSHIP_PLAN_ID"
            LEFT JOIN PUBLIC."AUDIT" 
                ON "AUDIT"."AUDIT_ID" = "USER"."AUDIT_ID"
        WHERE
            (P_USER_ID IS NULL OR "USER"."USER_ID" = P_USER_ID)
            AND (P_EMAIL IS NULL OR "USER"."EMAIL" ILIKE '%' || P_EMAIL || '%')
            AND (P_USERNAME IS NULL OR "USER"."USERNAME" ILIKE '%' || P_USERNAME || '%')
            AND (P_STATUS IS NULL OR "USER"."STATUS" = P_STATUS)
            AND (P_MEMBERSHIP_PLAN_ID IS NULL OR "USER"."MEMBERSHIP_PLAN_ID" = P_MEMBERSHIP_PLAN_ID)
        ORDER BY "USER"."USER_ID"
        LIMIT P_LIMIT
        OFFSET (P_PAGE - 1) * P_LIMIT
    ) t;
END;
$$;

ALTER PROCEDURE PUBLIC."GET_ACCOUNT_PAGINATED"(BIGINT, TEXT, TEXT, BIGINT, BIGINT, INT, INT)
OWNER TO POSTGRES;