CREATE OR REPLACE PROCEDURE PUBLIC."PATCH_ACCOUNT"(
    OUT DATA JSON,
    IN P_USER_ID BIGINT,
    IN P_EMAIL TEXT DEFAULT NULL,
    IN P_USERNAME TEXT DEFAULT NULL,
    IN P_HASHED_PASSWORD TEXT DEFAULT NULL,
    IN P_AVATAR_URL TEXT DEFAULT NULL,
    IN P_STATUS BIGINT DEFAULT NULL
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_AUDIT_ID BIGINT;
BEGIN
    SELECT "AUDIT_ID" INTO V_AUDIT_ID
    FROM PUBLIC."USER"
    WHERE "USER_ID" = P_USER_ID;

    UPDATE PUBLIC."USER"
    SET
        "EMAIL" = COALESCE(P_EMAIL, "EMAIL"),
        "USERNAME" = COALESCE(P_USERNAME, "USERNAME"),
        "HASHED_PASSWORD" = COALESCE(P_HASHED_PASSWORD, "HASHED_PASSWORD"),
        "AVATAR_URL" = COALESCE(P_AVATAR_URL, "AVATAR_URL"),
        "STATUS" = COALESCE(P_STATUS, "STATUS")
    WHERE "USER_ID" = P_USER_ID;

    UPDATE PUBLIC."AUDIT"
    SET "UPDATED_AT" = NOW()
    WHERE "AUDIT_ID" = V_AUDIT_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT
            "USER"."USER_ID",
            "USER"."AUDIT_ID",
            "USER"."EMAIL",
            "USER"."USERNAME",
            "USER"."HASHED_PASSWORD",
            "USER"."AVATAR_URL",
            "USER"."STATUS",
            "MEMBERSHIP_PLAN"."MEMBERSHIPPLAN_ID",
            "MEMBERSHIP_PLAN"."NAME",
            "MEMBERSHIP_PLAN"."DESCRIPTION",
            "MEMBERSHIP_PLAN"."AMOUNT",
            "AUDIT"."CREATED_AT" AS "USER_CREATED_AT",
            "AUDIT"."UPDATED_AT" AS "USER_UPDATED_AT"
        FROM
            PUBLIC."USER"
            LEFT JOIN PUBLIC."MEMBERSHIP_PLAN" 
                ON "MEMBERSHIP_PLAN"."MEMBERSHIPPLAN_ID" = "USER"."MEMBERSHIP_PLAN_ID"
            LEFT JOIN PUBLIC."AUDIT" 
                ON "AUDIT"."AUDIT_ID" = "USER"."AUDIT_ID"
        WHERE "USER"."USER_ID" = P_USER_ID
    ) t;

END;
$$;

ALTER PROCEDURE PUBLIC."PATCH_ACCOUNT"(BIGINT, TEXT, TEXT, TEXT, TEXT, BIGINT)
OWNER TO POSTGRES;
