CREATE OR REPLACE PROCEDURE PUBLIC."POST_ACCOUNT"(
    IN EMAIL TEXT,
    IN USERNAME TEXT,
    IN HASHED_PASSWORD TEXT,
    IN AVATAR_URL TEXT,
    IN STATUS BIGINT,
    OUT DATA JSON
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_USER_ID BIGINT;
    V_AUDIT_ID BIGINT;
BEGIN
    INSERT INTO PUBLIC."AUDIT" DEFAULT VALUES
    RETURNING "AUDIT_ID" INTO V_AUDIT_ID;

    INSERT INTO PUBLIC."USER" (
        "EMAIL",
        "USERNAME",
        "HASHED_PASSWORD",
        "AVATAR_URL",
        "STATUS",
        "AUDIT_ID"
    )
    VALUES (
        EMAIL,
        USERNAME,
        HASHED_PASSWORD,
        AVATAR_URL,
        STATUS,
        V_AUDIT_ID
    )
    RETURNING "USER_ID" INTO V_USER_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT
            "USER"."USER_ID",
            "USER"."AUDIT_ID",
            "USER"."EMAIL",
            "USER"."USERNAME",
            "USER"."HASHED_PASSWORD",
            "USER"."AVATAR_URL",
            "USER"."STATUS",
            "MEMBERSHIP_PLAN"."MEMBERSHIPPLAN_ID",
            "MEMBERSHIP_PLAN"."NAME",
            "MEMBERSHIP_PLAN"."DESCRIPTION",
            "MEMBERSHIP_PLAN"."AMOUNT",
            "AUDIT"."CREATED_AT" AS "USER_CREATED_AT",
            "AUDIT"."UPDATED_AT" AS "USER_UPDATED_AT"
        FROM
            PUBLIC."USER"
            LEFT JOIN PUBLIC."MEMBERSHIP_PLAN"
                ON "MEMBERSHIP_PLAN"."MEMBERSHIPPLAN_ID" = "USER"."MEMBERSHIP_PLAN_ID"
            LEFT JOIN PUBLIC."AUDIT"
                ON "AUDIT"."AUDIT_ID" = "USER"."AUDIT_ID"
        WHERE "USER"."USER_ID" = V_USER_ID
    ) t;
END;
$$;

ALTER PROCEDURE PUBLIC."POST_ACCOUNT"(TEXT, TEXT, TEXT, TEXT, BIGINT, JSON)
OWNER TO POSTGRES;
