CREATE OR REPLACE PROCEDURE PUBLIC."PUT_ACCOUNT"(
    OUT DATA JSON,
    IN P_USER_ID BIGINT,
    IN P_EMAIL TEXT,
    IN P_USERNAME TEXT,
    IN P_HASHED_PASSWORD TEXT,
    IN P_AVATAR_URL TEXT,
    IN P_STATUS BIGINT
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_AUDIT_ID BIGINT;
BEGIN
    SELECT "AUDIT_ID" INTO V_AUDIT_ID
    FROM PUBLIC."USER"
    WHERE "USER_ID" = P_USER_ID;
    UPDATE PUBLIC."USER"
    SET
        "EMAIL" = P_EMAIL,
        "USERNAME" = P_USERNAME,
        "HASHED_PASSWORD" = P_HASHED_PASSWORD,
        "AVATAR_URL" = P_AVATAR_URL,
        "STATUS" = P_STATUS
    WHERE "USER_ID" = P_USER_ID;

    UPDATE PUBLIC."AUDIT"
    SET "UPDATED_AT" = NOW()
    WHERE "AUDIT_ID" = V_AUDIT_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT
            "USER"."USER_ID",
            "USER"."AUDIT_ID",
            "USER"."EMAIL",
            "USER"."USERNAME",
            "USER"."HASHED_PASSWORD",
            "USER"."AVATAR_URL",
            "USER"."STATUS",
            "MEMBERSHIP_PLAN"."MEMBERSHIPPLAN_ID",
            "MEMBERSHIP_PLAN"."NAME",
            "MEMBERSHIP_PLAN"."DESCRIPTION",
            "MEMBERSHIP_PLAN"."AMOUNT",
            "AUDIT"."CREATED_AT" AS "USER_CREATED_AT",
            "AUDIT"."UPDATED_AT" AS "USER_UPDATED_AT"
        FROM
            PUBLIC."USER"
            LEFT JOIN PUBLIC."MEMBERSHIP_PLAN" 
                ON "MEMBERSHIP_PLAN"."MEMBERSHIPPLAN_ID" = "USER"."MEMBERSHIP_PLAN_ID"
            LEFT JOIN PUBLIC."AUDIT" 
                ON "AUDIT"."AUDIT_ID" = "USER"."AUDIT_ID"
        WHERE "USER"."USER_ID" = P_USER_ID
    ) t;

END;
$$;

ALTER PROCEDURE PUBLIC."PUT_ACCOUNT"(BIGINT, TEXT, TEXT, TEXT, TEXT, BIGINT)
OWNER TO POSTGRES;
