CREATE OR REPLACE PROCEDURE PUBLIC."DELETE_USER_PROJECT" (
    IN P_USER_PROJECT_ID BIGINT,
    OUT DATA JSON
)
LANGUAGE PLPGSQL
AS $$
BEGIN
    DELETE FROM PUBLIC."USER_PROJECT" up
    WHERE "USER_PROJECT_ID" = P_USER_PROJECT_ID
    RETURNING to_json(up.*) INTO DATA;
END;
$$;
