CREATE OR REPLACE PROCEDURE PUBLIC."GET_USER_PROJECT" (
    OUT DATA JSON,
    IN P_USER_PROJECT_ID BIGINT DEFAULT NULL,
    IN P_USER_ID_FK BIGINT DEFAULT NULL,
    IN P_ROL_PROYECT BIGINT DEFAULT NULL,
    IN P_PRODUCTIVITY NUMERIC DEFAULT NULL,
    IN P_PAGE INT DEFAULT 1,
    IN P_LIMIT INT DEFAULT 10
)
LANGUAGE PLPGSQL
AS $$
BEGIN
    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT *
        FROM PUBLIC."USER_PROJECT" up
        WHERE (P_USER_PROJECT_ID IS NULL OR up."USER_PROJECT_ID" = P_USER_PROJECT_ID)
          AND (P_USER_ID_FK IS NULL OR up."USER_ID_FK" = P_USER_ID_FK)
          AND (P_ROL_PROYECT IS NULL OR up."ROL_PROYECT" = P_ROL_PROYECT)
          AND (P_PRODUCTIVITY IS NULL OR up."PRODUCTIVITY" = P_PRODUCTIVITY)
        ORDER BY up."USER_PROJECT_ID"
        LIMIT P_LIMIT OFFSET (P_PAGE - 1) * P_LIMIT
    ) t;
END;
$$;
