CREATE OR REPLACE PROCEDURE PUBLIC."PATCH_USER_PROJECT" (
	OUT DATA JSON,
	IN P_USER_PROJECT_ID BIGINT,
	IN P_USER_ID_FK BIGINT DEFAULT NULL,
	IN P_ROL_PROYECT BIGINT DEFAULT NULL,
	IN P_PRODUCTIVITY NUMERIC(5, 2) DEFAULT NULL
) LANGUAGE PLPGSQL AS $$
BEGIN
    UPDATE PUBLIC."USER_PROJECT"
    SET "USER_ID_FK"   = COALESCE(P_USER_ID_FK, "USER_ID_FK"),
        "ROL_PROYECT"  = COALESCE(P_ROL_PROYECT, "ROL_PROYECT"),
        "PRODUCTIVITY" = COALESCE(P_PRODUCTIVITY, "PRODUCTIVITY")
    WHERE "USER_PROJECT_ID" = P_USER_PROJECT_ID;

    CALL PUBLIC."GET_USER_PROJECT"(DATA, P_USER_PROJECT_ID, NULL, NULL, 1, 1);
END;
$$;