CREATE OR REPLACE PROCEDURE PUBLIC."POST_USER_PROJECT" (
	IN P_USER_ID_FK BIGINT,
	IN P_ROL_PROYECT BIGINT,
	IN P_PRODUCTIVITY NUMERIC(5, 2),
	OUT DATA JSON
) LANGUAGE PLPGSQL AS $$
DECLARE
    V_ID BIGINT;
BEGIN
    INSERT INTO PUBLIC."USER_PROJECT" ("USER_ID_FK", "ROL_PROYECT", "PRODUCTIVITY")
    VALUES (P_USER_ID_FK, P_ROL_PROYECT, P_PRODUCTIVITY)
    RETURNING "USER_PROJECT_ID" INTO V_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT up."USER_PROJECT_ID", up."USER_ID_FK", up."ROL_PROYECT", up."PRODUCTIVITY"
        FROM PUBLIC."USER_PROJECT" up
        WHERE up."USER_PROJECT_ID" = V_ID
    ) t;
END;
$$;