CREATE OR REPLACE PROCEDURE PUBLIC."PUT_USER_PROJECT" (
	IN P_USER_PROJECT_ID BIGINT,
	IN P_USER_ID_FK BIGINT,
	IN P_ROL_PROYECT BIGINT,
	IN P_PRODUCTIVITY NUMERIC(5, 2),
	OUT DATA JSON
) LANGUAGE PLPGSQL AS $$
BEGIN
    UPDATE PUBLIC."USER_PROJECT"
    SET "USER_ID_FK" = P_USER_ID_FK,
        "ROL_PROYECT" = P_ROL_PROYECT,
        "PRODUCTIVITY" = P_PRODUCTIVITY
    WHERE "USER_PROJECT_ID" = P_USER_PROJECT_ID;

    PERFORM pg_sleep(0.05);

    CALL PUBLIC."GET_USER_PROJECT"(DATA, P_USER_PROJECT_ID, NULL, NULL, 1, 1);
END;
$$;