CREATE OR REPLACE PROCEDURE PUBLIC."DELETE_PROJECT" (
    IN P_PROJECT_ID BIGINT,
    OUT DATA JSON
)
LANGUAGE PLPGSQL
AS $$
BEGIN
    DELETE FROM PUBLIC."PROJECT" p
    WHERE "PROJECT_ID" = P_PROJECT_ID
    RETURNING to_json(p.*) INTO DATA;
END;
$$;
