CREATE OR REPLACE PROCEDURE PUBLIC."GET_PROJECT"(
    OUT DATA JSON,
    IN P_PROJECT_ID BIGINT DEFAULT NULL,
    IN P_NAME TEXT DEFAULT NULL,
    IN P_DESCRIPTION TEXT DEFAULT NULL,
    IN P_USER_PROJECT_ID_FK BIGINT DEFAULT NULL,
    IN P_DATE_INIT_START DATE DEFAULT NULL,
    IN P_DATE_INIT_END DATE DEFAULT NULL,
    IN P_DATE_END_START DATE DEFAULT NULL,
    IN P_DATE_END_END DATE DEFAULT NULL,
    IN P_STATUS BIGINT DEFAULT NULL,
    IN P_PROGRESS_MIN NUMERIC DEFAULT NULL,
    IN P_PROGRESS_MAX NUMERIC DEFAULT NULL,
    IN P_PAGE INT DEFAULT 1,
    IN P_LIMIT INT DEFAULT 10
)
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT *
        FROM PUBLIC."PROJECT" p
        WHERE (P_PROJECT_ID IS NULL OR p."PROJECT_ID" = P_PROJECT_ID)
          AND (P_NAME IS NULL OR p."NAME" ILIKE '%' || P_NAME || '%')
          AND (P_DESCRIPTION IS NULL OR p."DESCRIPTION" ILIKE '%' || P_DESCRIPTION || '%')
          AND (P_USER_PROJECT_ID_FK IS NULL OR p."USER_PROJECT_ID_FK" = P_USER_PROJECT_ID_FK)
          AND (P_DATE_INIT_START IS NULL OR p."DATE_INIT" >= P_DATE_INIT_START)
          AND (P_DATE_INIT_END IS NULL OR p."DATE_INIT" <= P_DATE_INIT_END)
          AND (P_DATE_END_START IS NULL OR p."DATE_END" >= P_DATE_END_START)
          AND (P_DATE_END_END IS NULL OR p."DATE_END" <= P_DATE_END_END)
          AND (P_STATUS IS NULL OR p."STATUS" = P_STATUS)
          AND (P_PROGRESS_MIN IS NULL OR p."PROGRESS" >= P_PROGRESS_MIN)
          AND (P_PROGRESS_MAX IS NULL OR p."PROGRESS" <= P_PROGRESS_MAX)
        ORDER BY p."PROJECT_ID"
        LIMIT P_LIMIT OFFSET (P_PAGE - 1) * P_LIMIT
    ) t;
END;
$$;
