CREATE OR REPLACE PROCEDURE PUBLIC."PATCH_PROJECT" (
	OUT DATA JSON,
	IN P_PROJECT_ID BIGINT,
	IN P_NAME TEXT DEFAULT NULL,
	IN P_DESCRIPTION TEXT DEFAULT NULL,
	IN P_USER_PROJECT_ID_FK BIGINT DEFAULT NULL,
	IN P_DATE_INIT DATE DEFAULT NULL,
	IN P_DATE_END DATE DEFAULT NULL,
	IN P_STATUS BIGINT DEFAULT NULL,
	IN P_PROGRESS NUMERIC(5, 2) DEFAULT NULL
) LANGUAGE PLPGSQL AS $$
BEGIN
    UPDATE PUBLIC."PROJECT"
    SET "NAME" = COALESCE(P_NAME, "NAME"),
        "DESCRIPTION" = COALESCE(P_DESCRIPTION, "DESCRIPTION"),
        "USER_PROJECT_ID_FK" = COALESCE(P_USER_PROJECT_ID_FK, "USER_PROJECT_ID_FK"),
        "DATE_INIT" = COALESCE(P_DATE_INIT, "DATE_INIT"),
        "DATE_END" = COALESCE(P_DATE_END, "DATE_END"),
        "STATUS" = COALESCE(P_STATUS, "STATUS"),
        "PROGRESS" = COALESCE(P_PROGRESS, "PROGRESS")
    WHERE "PROJECT_ID" = P_PROJECT_ID;

    CALL PUBLIC."GET_PROJECT"(DATA, P_PROJECT_ID, NULL, NULL, NULL, 1, 1);
END;
$$;