CREATE OR REPLACE PROCEDURE PUBLIC."POST_PROJECT"(
    IN P_NAME TEXT,
    IN P_DESCRIPTION TEXT,
    IN P_USER_PROJECT_ID_FK BIGINT,
    IN P_DATE_INIT DATE,
    IN P_DATE_END DATE,
    IN P_STATUS BIGINT,
    IN P_PROGRESS NUMERIC(5,2),
    OUT DATA JSON
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_ID BIGINT;
BEGIN
    INSERT INTO PUBLIC."PROJECT" ("NAME", "DESCRIPTION", "USER_PROJECT_ID_FK",
                                  "DATE_INIT", "DATE_END", "STATUS", "PROGRESS")
    VALUES (P_NAME, P_DESCRIPTION, P_USER_PROJECT_ID_FK,
            P_DATE_INIT, P_DATE_END, P_STATUS, P_PROGRESS)
    RETURNING "PROJECT_ID" INTO V_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT p."PROJECT_ID", p."NAME", p."DESCRIPTION",
               p."USER_PROJECT_ID_FK", p."DATE_INIT", p."DATE_END",
               p."STATUS", p."PROGRESS"
        FROM PUBLIC."PROJECT" p
        WHERE p."PROJECT_ID" = V_ID
    ) t;
END;
$$;