CREATE OR REPLACE PROCEDURE PUBLIC."PUT_PROJECT"(
    IN P_PROJECT_ID BIGINT,
    IN P_NAME TEXT,
    IN P_DESCRIPTION TEXT,
    IN P_USER_PROJECT_ID_FK BIGINT,
    IN P_DATE_INIT DATE,
    IN P_DATE_END DATE,
    IN P_STATUS BIGINT,
    IN P_PROGRESS NUMERIC(5,2),
    OUT DATA JSON
)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE PUBLIC."PROJECT"
    SET "NAME" = P_NAME,
        "DESCRIPTION" = P_DESCRIPTION,
        "USER_PROJECT_ID_FK" = P_USER_PROJECT_ID_FK,
        "DATE_INIT" = P_DATE_INIT,
        "DATE_END" = P_DATE_END,
        "STATUS" = P_STATUS,
        "PROGRESS" = P_PROGRESS
    WHERE "PROJECT_ID" = P_PROJECT_ID;

    CALL PUBLIC."GET_PROJECT"(DATA, P_PROJECT_ID, NULL, NULL, NULL, 1, 1);
END;
$$;