CREATE OR REPLACE PROCEDURE PUBLIC."DELETE_PAYMENT_INFO"(
    IN P_PAYMENT_INFO_ID BIGINT,
    OUT DATA JSON
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_AUDIT_ID BIGINT;
BEGIN
    SELECT "AUDIT_ID" INTO V_AUDIT_ID
    FROM PUBLIC."PAYMENT_INFO"
    WHERE "PAYMENT_INFO_ID" = P_PAYMENT_INFO_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT pi."PAYMENT_INFO_ID", pi."USER_ID", pi."METHOD", pi."LAST_FOUR_DIGITS",
               pi."STATUS", pi."NEXT_PAYMENT_DATE", pi."AUDIT_ID",
               a."CREATED_AT", a."UPDATED_AT"
        FROM PUBLIC."PAYMENT_INFO" pi
        JOIN PUBLIC."AUDIT" a ON pi."AUDIT_ID" = a."AUDIT_ID"
        WHERE pi."PAYMENT_INFO_ID" = P_PAYMENT_INFO_ID
    ) t;

    DELETE FROM PUBLIC."PAYMENT_INFO"
    WHERE "PAYMENT_INFO_ID" = P_PAYMENT_INFO_ID;

    DELETE FROM PUBLIC."AUDIT"
    WHERE "AUDIT_ID" = V_AUDIT_ID;
END;
$$;
