CREATE OR REPLACE PROCEDURE PUBLIC."GET_PAYMENT_INFO"(
    OUT DATA JSON,
    IN P_PAYMENT_INFO_ID BIGINT DEFAULT NULL,
    IN P_USER_ID BIGINT DEFAULT NULL,
    IN P_METHOD BIGINT DEFAULT NULL,
    IN P_STATUS BIGINT DEFAULT NULL,
    IN P_NEXT_PAYMENT_DATE DATE DEFAULT NULL,
    IN P_PAGE INT DEFAULT 1,
    IN P_LIMIT INT DEFAULT 10
)
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT pi."PAYMENT_INFO_ID", pi."USER_ID", pi."METHOD", pi."LAST_FOUR_DIGITS",
               pi."STATUS", pi."NEXT_PAYMENT_DATE", pi."AUDIT_ID",
               a."CREATED_AT", a."UPDATED_AT"
        FROM PUBLIC."PAYMENT_INFO" pi
        JOIN PUBLIC."AUDIT" a ON pi."AUDIT_ID" = a."AUDIT_ID"
        WHERE (P_PAYMENT_INFO_ID IS NULL OR pi."PAYMENT_INFO_ID" = P_PAYMENT_INFO_ID)
          AND (P_USER_ID IS NULL OR pi."USER_ID" = P_USER_ID)
          AND (P_METHOD IS NULL OR pi."METHOD" = P_METHOD)
          AND (P_STATUS IS NULL OR pi."STATUS" = P_STATUS)
          AND (P_NEXT_PAYMENT_DATE IS NULL OR pi."NEXT_PAYMENT_DATE" = P_NEXT_PAYMENT_DATE)
        ORDER BY pi."PAYMENT_INFO_ID"
        LIMIT P_LIMIT OFFSET (P_PAGE - 1) * P_LIMIT
    ) t;
END;
$$;
