CREATE OR REPLACE PROCEDURE PUBLIC."PATCH_PAYMENT_INFO" (
	OUT DATA JSON,
	IN P_PAYMENT_INFO_ID BIGINT,
	IN P_USER_ID BIGINT DEFAULT NULL,
	IN P_METHOD BIGINT DEFAULT NULL,
	IN P_LAST_FOUR_DIGITS TEXT DEFAULT NULL,
	IN P_STATUS BIGINT DEFAULT NULL,
	IN P_NEXT_PAYMENT_DATE DATE DEFAULT NULL
) LANGUAGE PLPGSQL AS $$
DECLARE
    V_AUDIT_ID BIGINT;
BEGIN
    SELECT "AUDIT_ID" INTO V_AUDIT_ID
    FROM PUBLIC."PAYMENT_INFO"
    WHERE "PAYMENT_INFO_ID" = P_PAYMENT_INFO_ID;

    UPDATE PUBLIC."PAYMENT_INFO"
    SET "USER_ID" = COALESCE(P_USER_ID, "USER_ID"),
        "METHOD" = COALESCE(P_METHOD, "METHOD"),
        "LAST_FOUR_DIGITS" = COALESCE(P_LAST_FOUR_DIGITS, "LAST_FOUR_DIGITS"),
        "STATUS" = COALESCE(P_STATUS, "STATUS"),
        "NEXT_PAYMENT_DATE" = COALESCE(P_NEXT_PAYMENT_DATE, "NEXT_PAYMENT_DATE")
    WHERE "PAYMENT_INFO_ID" = P_PAYMENT_INFO_ID;

    UPDATE PUBLIC."AUDIT"
    SET "UPDATED_AT" = CURRENT_TIMESTAMP
    WHERE "AUDIT_ID" = V_AUDIT_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT pi."PAYMENT_INFO_ID", pi."USER_ID", pi."METHOD", pi."LAST_FOUR_DIGITS",
               pi."STATUS", pi."NEXT_PAYMENT_DATE", pi."AUDIT_ID",
               a."CREATED_AT", a."UPDATED_AT"
        FROM PUBLIC."PAYMENT_INFO" pi
        JOIN PUBLIC."AUDIT" a ON pi."AUDIT_ID" = a."AUDIT_ID"
        WHERE pi."PAYMENT_INFO_ID" = P_PAYMENT_INFO_ID
    ) t;
END;
$$;