CREATE OR REPLACE PROCEDURE PUBLIC."POST_PAYMENT_INFO"(
    IN P_USER_ID BIGINT,
    IN P_METHOD BIGINT,
    IN P_LAST_FOUR_DIGITS TEXT,
    IN P_STATUS BIGINT,
    IN P_NEXT_PAYMENT_DATE DATE,
    OUT DATA JSON
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_ID BIGINT;
    V_AUDIT_ID BIGINT;
BEGIN
    INSERT INTO PUBLIC."AUDIT" ("CREATED_AT", "UPDATED_AT")
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    RETURNING "AUDIT_ID" INTO V_AUDIT_ID;

    INSERT INTO PUBLIC."PAYMENT_INFO" ("USER_ID", "METHOD", "LAST_FOUR_DIGITS", "STATUS", "NEXT_PAYMENT_DATE", "AUDIT_ID")
    VALUES (P_USER_ID, P_METHOD, P_LAST_FOUR_DIGITS, P_STATUS, P_NEXT_PAYMENT_DATE, V_AUDIT_ID)
    RETURNING "PAYMENT_INFO_ID" INTO V_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT pi."PAYMENT_INFO_ID", pi."USER_ID", pi."METHOD", pi."LAST_FOUR_DIGITS",
               pi."STATUS", pi."NEXT_PAYMENT_DATE", pi."AUDIT_ID",
               a."CREATED_AT", a."UPDATED_AT"
        FROM PUBLIC."PAYMENT_INFO" pi
        JOIN PUBLIC."AUDIT" a ON pi."AUDIT_ID" = a."AUDIT_ID"
        WHERE pi."PAYMENT_INFO_ID" = V_ID
    ) t;
END;
$$;
