CREATE OR REPLACE PROCEDURE PUBLIC."PUT_PAYMENT_INFO"(
    IN P_PAYMENT_INFO_ID BIGINT,
    IN P_USER_ID BIGINT,
    IN P_METHOD BIGINT,
    IN P_LAST_FOUR_DIGITS TEXT,
    IN P_STATUS BIGINT,
    IN P_NEXT_PAYMENT_DATE DATE,
    OUT DATA JSON
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_AUDIT_ID BIGINT;
BEGIN
    SELECT "AUDIT_ID" INTO V_AUDIT_ID
    FROM PUBLIC."PAYMENT_INFO"
    WHERE "PAYMENT_INFO_ID" = P_PAYMENT_INFO_ID;

    UPDATE PUBLIC."PAYMENT_INFO"
    SET "USER_ID" = P_USER_ID,
        "METHOD" = P_METHOD,
        "LAST_FOUR_DIGITS" = P_LAST_FOUR_DIGITS,
        "STATUS" = P_STATUS,
        "NEXT_PAYMENT_DATE" = P_NEXT_PAYMENT_DATE
    WHERE "PAYMENT_INFO_ID" = P_PAYMENT_INFO_ID;

    UPDATE PUBLIC."AUDIT"
    SET "UPDATED_AT" = CURRENT_TIMESTAMP
    WHERE "AUDIT_ID" = V_AUDIT_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT pi."PAYMENT_INFO_ID", pi."USER_ID", pi."METHOD", pi."LAST_FOUR_DIGITS",
               pi."STATUS", pi."NEXT_PAYMENT_DATE", pi."AUDIT_ID",
               a."CREATED_AT", a."UPDATED_AT"
        FROM PUBLIC."PAYMENT_INFO" pi
        JOIN PUBLIC."AUDIT" a ON pi."AUDIT_ID" = a."AUDIT_ID"
        WHERE pi."PAYMENT_INFO_ID" = P_PAYMENT_INFO_ID
    ) t;
END;
$$;
