CREATE OR REPLACE PROCEDURE PUBLIC."DELETE_ISSUE_TYPE" (
    IN P_ISSUE_TYPE_ID BIGINT,
    OUT DATA JSON
)
LANGUAGE PLPGSQL
AS $$
BEGIN
    DELETE FROM PUBLIC."ISSUE_TYPE" it
    WHERE "ISSUE_TYPE_ID" = P_ISSUE_TYPE_ID
    RETURNING to_json(it.*) INTO DATA;
END;
$$;
