CREATE OR REPLACE PROCEDURE PUBLIC."GET_ISSUE_TYPE" (
	OUT DATA JSON,
	IN P_ISSUE_TYPE_ID BIGINT DEFAULT NULL,
	IN P_STATUS BIGINT DEFAULT NULL,
	IN P_PRIORITY BIGINT DEFAULT NULL,
	IN P_PAGE INT DEFAULT 1,
	IN P_LIMIT INT DEFAULT 10
) LANGUAGE PLPGSQL AS $$
BEGIN
    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT it."ISSUE_TYPE_ID", it."STATUS", it."PRIORITY"
        FROM PUBLIC."ISSUE_TYPE" it
        WHERE (P_ISSUE_TYPE_ID IS NULL OR it."ISSUE_TYPE_ID" = P_ISSUE_TYPE_ID)
          AND (P_STATUS IS NULL OR it."STATUS" = P_STATUS)
          AND (P_PRIORITY IS NULL OR it."PRIORITY" = P_PRIORITY)
        ORDER BY it."ISSUE_TYPE_ID"
        LIMIT P_LIMIT OFFSET (P_PAGE - 1) * P_LIMIT
    ) t;
END;
$$;