CREATE OR REPLACE PROCEDURE PUBLIC."PATCH_ISSUE_TYPE" (
	OUT DATA JSON,
	IN P_ISSUE_TYPE_ID BIGINT,
	IN P_STATUS BIGINT DEFAULT NULL,
	IN P_PRIORITY BIGINT DEFAULT NULL
) LANGUAGE PLPGSQL AS $$
BEGIN
    UPDATE PUBLIC."ISSUE_TYPE" i
    SET "STATUS" = COALESCE(P_STATUS, "STATUS"),
        "PRIORITY" = COALESCE(P_PRIORITY, "PRIORITY")
    WHERE "ISSUE_TYPE_ID" = P_ISSUE_TYPE_ID
    RETURNING row_to_json(i) INTO DATA;
END;
$$;