CREATE OR REPLACE PROCEDURE PUBLIC."POST_ISSUE_TYPE" (
	IN P_STATUS BIGINT,
	IN P_PRIORITY BIGINT,
	OUT DATA JSON
) LANGUAGE PLPGSQL AS $$
DECLARE
    V_ID BIGINT;
BEGIN
    INSERT INTO PUBLIC."ISSUE_TYPE" ("STATUS", "PRIORITY")
    VALUES (P_STATUS, P_PRIORITY)
    RETURNING "ISSUE_TYPE_ID" INTO V_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT it."ISSUE_TYPE_ID", it."STATUS", it."PRIORITY"
        FROM PUBLIC."ISSUE_TYPE" it
        WHERE it."ISSUE_TYPE_ID" = V_ID
    ) t;
END;
$$;