CREATE OR REPLACE PROCEDURE PUBLIC."PUT_ISSUE_TYPE" (
	IN P_ISSUE_TYPE_ID BIGINT,
	IN P_STATUS BIGINT,
	IN P_PRIORITY BIGINT,
	OUT DATA JSON
) LANGUAGE PLPGSQL AS $$
BEGIN
    UPDATE PUBLIC."ISSUE_TYPE" I
    SET "STATUS" = P_STATUS,
        "PRIORITY" = P_PRIORITY
    WHERE "ISSUE_TYPE_ID" = P_ISSUE_TYPE_ID
    RETURNING row_to_json(i) INTO DATA;
END;
$$;
