CREATE OR REPLACE PROCEDURE PUBLIC."DELETE_ISSUE" (
    IN P_ISSUE_ID BIGINT,
    OUT DATA JSON
)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM PUBLIC."ISSUE" i
    WHERE "ISSUE_ID" = P_ISSUE_ID
    RETURNING to_json(i.*) INTO DATA;
END;
$$;
