CREATE OR REPLACE PROCEDURE PUBLIC."GET_ISSUE" (
    OUT DATA JSON,
    IN P_ISSUE_ID BIGINT DEFAULT NULL,
    IN P_SUMMARY TEXT DEFAULT NULL,
    IN P_DESCRIPTION TEXT DEFAULT NULL,
    IN P_AUDIT_ID BIGINT DEFAULT NULL,
    IN P_RESOLVE_AT DATE DEFAULT NULL,
    IN P_DUE_DATE DATE DEFAULT NULL,
    IN P_VOTES BIGINT DEFAULT NULL,
    IN P_ORIGINAL_ESTIMATION BIGINT DEFAULT NULL,
    IN P_CUSTOM_START_DATE DATE DEFAULT NULL,
    IN P_STORY_POINT_ESTIMATE BIGINT DEFAULT NULL,
    IN P_PARENT_SUMMARY BIGINT DEFAULT NULL,
    IN P_ISSUE_TYPE BIGINT DEFAULT NULL,
    IN P_PROJECT_ID_FK BIGINT DEFAULT NULL,
    IN P_USER_ASSIGNED_FK BIGINT DEFAULT NULL,
    IN P_USER_CREATOR_ISSUE_FK BIGINT DEFAULT NULL,
    IN P_USER_INFORMATOR_FK BIGINT DEFAULT NULL,
    IN P_SPRINT_ID_FK BIGINT DEFAULT NULL,
    IN P_STATUS_ISSUE BIGINT DEFAULT NULL,
    IN P_PAGE INT DEFAULT 1,
    IN P_LIMIT INT DEFAULT 10
)
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT *
        FROM PUBLIC."ISSUE"
        WHERE (P_ISSUE_ID IS NULL OR "ISSUE_ID" = P_ISSUE_ID)
          AND (P_SUMMARY IS NULL OR "SUMMARY" ILIKE '%' || P_SUMMARY || '%')
          AND (P_DESCRIPTION IS NULL OR "DESCRIPTION" ILIKE '%' || P_DESCRIPTION || '%')
          AND (P_AUDIT_ID IS NULL OR "AUDIT_ID_FK" = P_AUDIT_ID)
          AND (P_RESOLVE_AT IS NULL OR "RESOLVE_AT" = P_RESOLVE_AT)
          AND (P_DUE_DATE IS NULL OR "DUE_DATE" = P_DUE_DATE)
          AND (P_VOTES IS NULL OR "VOTES" = P_VOTES)
          AND (P_ORIGINAL_ESTIMATION IS NULL OR "ORIGINAL_ESTIMATION" = P_ORIGINAL_ESTIMATION)
          AND (P_CUSTOM_START_DATE IS NULL OR "CUSTOM_START_DATE" = P_CUSTOM_START_DATE)
          AND (P_STORY_POINT_ESTIMATE IS NULL OR "STORY_POINT_ESTIMATE" = P_STORY_POINT_ESTIMATE)
          AND (P_PARENT_SUMMARY IS NULL OR "PARENT_SUMMARY_FK" = P_PARENT_SUMMARY)
          AND (P_ISSUE_TYPE IS NULL OR "ISSUE_TYPE" = P_ISSUE_TYPE)
          AND (P_PROJECT_ID_FK IS NULL OR "PROJECT_ID_FK" = P_PROJECT_ID_FK)
          AND (P_USER_ASSIGNED_FK IS NULL OR "USER_ASSIGNED_FK" = P_USER_ASSIGNED_FK)
          AND (P_USER_CREATOR_ISSUE_FK IS NULL OR "USER_CREATOR_ISSUE_FK" = P_USER_CREATOR_ISSUE_FK)
          AND (P_USER_INFORMATOR_FK IS NULL OR "USER_INFORMATOR_ISSUE_FK" = P_USER_INFORMATOR_FK)
          AND (P_SPRINT_ID_FK IS NULL OR "SPRINT_ID_FK" = P_SPRINT_ID_FK)
          AND (P_STATUS_ISSUE IS NULL OR "STATUS_ISSUE" = P_STATUS_ISSUE)
        ORDER BY "ISSUE_ID"
        LIMIT P_LIMIT OFFSET (P_PAGE - 1) * P_LIMIT
    ) t;
END;
$$;
