CREATE OR REPLACE PROCEDURE PUBLIC."PATCH_ISSUE" (
    OUT DATA JSON,
    IN P_ISSUE_ID BIGINT,
    IN P_SUMMARY TEXT DEFAULT NULL,
    IN P_DESCRIPTION TEXT DEFAULT NULL,
    IN P_AUDIT_ID BIGINT DEFAULT NULL,
    IN P_RESOLVE_AT DATE DEFAULT NULL,
    IN P_DUE_DATE DATE DEFAULT NULL,
    IN P_VOTES BIGINT DEFAULT NULL,
    IN P_ORIGINAL_ESTIMATION BIGINT DEFAULT NULL,
    IN P_CUSTOM_START_DATE DATE DEFAULT NULL,
    IN P_STORY_POINT_ESTIMATE BIGINT DEFAULT NULL,
    IN P_PARENT_SUMMARY BIGINT DEFAULT NULL,
    IN P_ISSUE_TYPE BIGINT DEFAULT NULL,
    IN P_PROJECT_ID BIGINT DEFAULT NULL,
    IN P_USER_ASSIGNED BIGINT DEFAULT NULL,
    IN P_USER_CREATOR BIGINT DEFAULT NULL,
    IN P_USER_INFORMATOR BIGINT DEFAULT NULL,
    IN P_SPRINT_ID BIGINT DEFAULT NULL,
    IN P_STATUS BIGINT DEFAULT NULL
)
LANGUAGE PLPGSQL
AS $$
BEGIN
    UPDATE PUBLIC."ISSUE"
    SET "SUMMARY" = COALESCE(P_SUMMARY, "SUMMARY"),
        "DESCRIPTION" = COALESCE(P_DESCRIPTION, "DESCRIPTION"),
        "AUDIT_ID_FK" = COALESCE(P_AUDIT_ID, "AUDIT_ID_FK"),
        "RESOLVE_AT" = COALESCE(P_RESOLVE_AT, "RESOLVE_AT"),
        "DUE_DATE" = COALESCE(P_DUE_DATE, "DUE_DATE"),
        "VOTES" = COALESCE(P_VOTES, "VOTES"),
        "ORIGINAL_ESTIMATION" = COALESCE(P_ORIGINAL_ESTIMATION, "ORIGINAL_ESTIMATION"),
        "CUSTOM_START_DATE" = COALESCE(P_CUSTOM_START_DATE, "CUSTOM_START_DATE"),
        "STORY_POINT_ESTIMATE" = COALESCE(P_STORY_POINT_ESTIMATE, "STORY_POINT_ESTIMATE"),
        "PARENT_SUMMARY_FK" = CASE WHEN P_PARENT_SUMMARY = -1 THEN NULL ELSE COALESCE(P_PARENT_SUMMARY, "PARENT_SUMMARY_FK") END,
        "ISSUE_TYPE" = CASE WHEN P_ISSUE_TYPE = -1 THEN NULL ELSE COALESCE(P_ISSUE_TYPE, "ISSUE_TYPE") END,
        "PROJECT_ID_FK" = CASE WHEN P_PROJECT_ID = -1 THEN NULL ELSE COALESCE(P_PROJECT_ID, "PROJECT_ID_FK") END,
        "USER_ASSIGNED_FK" = CASE WHEN P_USER_ASSIGNED = -1 THEN NULL ELSE COALESCE(P_USER_ASSIGNED, "USER_ASSIGNED_FK") END,
        "USER_CREATOR_ISSUE_FK" = CASE WHEN P_USER_CREATOR = -1 THEN NULL ELSE COALESCE(P_USER_CREATOR, "USER_CREATOR_ISSUE_FK") END,
        "USER_INFORMATOR_ISSUE_FK" = CASE WHEN P_USER_INFORMATOR = -1 THEN NULL ELSE COALESCE(P_USER_INFORMATOR, "USER_INFORMATOR_ISSUE_FK") END,
        "SPRINT_ID_FK" =  CASE WHEN P_SPRINT_ID = -1 THEN NULL ELSE COALESCE(P_SPRINT_ID, "SPRINT_ID_FK") END,
        "STATUS_ISSUE" = COALESCE(P_STATUS, "STATUS_ISSUE")
    WHERE "ISSUE_ID" = P_ISSUE_ID;

    SELECT to_json(i.*)
    INTO DATA
    FROM PUBLIC."ISSUE" i
    WHERE i."ISSUE_ID" = P_ISSUE_ID;
END;
$$;
