CREATE OR REPLACE PROCEDURE PUBLIC."POST_ISSUE" (
    IN P_SUMMARY TEXT,
    IN P_DESCRIPTION TEXT,
    IN P_RESOLVE_AT DATE,
    IN P_DUE_DATE DATE,
    IN P_VOTES BIGINT,
    IN P_ORIGINAL_ESTIMATION BIGINT,
    IN P_CUSTOM_START_DATE DATE,
    IN P_STORY_POINT_ESTIMATE BIGINT,
    IN P_PARENT_SUMMARY BIGINT,
    IN P_ISSUE_TYPE BIGINT,
    IN P_PROJECT_ID BIGINT,
    IN P_USER_ASSIGNED BIGINT,
    IN P_USER_CREATOR BIGINT,
    IN P_USER_INFORMATOR BIGINT,
    IN P_SPRINT_ID BIGINT,
    IN P_STATUS BIGINT,
    OUT DATA JSON
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_AUDIT_ID BIGINT;
    V_ISSUE_ID BIGINT;
BEGIN
    INSERT INTO PUBLIC."AUDIT"("CREATED_AT", "UPDATED_AT")
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    RETURNING "AUDIT_ID" INTO V_AUDIT_ID;

    INSERT INTO PUBLIC."ISSUE"(
        "SUMMARY","DESCRIPTION","AUDIT_ID_FK","RESOLVE_AT","DUE_DATE",
        "VOTES","ORIGINAL_ESTIMATION","CUSTOM_START_DATE","STORY_POINT_ESTIMATE",
        "PARENT_SUMMARY_FK","ISSUE_TYPE","PROJECT_ID_FK","USER_ASSIGNED_FK",
        "USER_CREATOR_ISSUE_FK","USER_INFORMATOR_ISSUE_FK","SPRINT_ID_FK","STATUS_ISSUE")
    VALUES (
        P_SUMMARY,P_DESCRIPTION,V_AUDIT_ID,P_RESOLVE_AT,P_DUE_DATE,
        P_VOTES,P_ORIGINAL_ESTIMATION,P_CUSTOM_START_DATE,P_STORY_POINT_ESTIMATE,
        P_PARENT_SUMMARY,P_ISSUE_TYPE,P_PROJECT_ID,P_USER_ASSIGNED,
        P_USER_CREATOR,P_USER_INFORMATOR,P_SPRINT_ID,P_STATUS)
    RETURNING "ISSUE_ID" INTO V_ISSUE_ID;

    SELECT to_json(i.*)
    INTO DATA
    FROM PUBLIC."ISSUE" i
    WHERE i."ISSUE_ID" = V_ISSUE_ID;
END;
$$;
