CREATE OR REPLACE PROCEDURE PUBLIC."PUT_ISSUE" (
	IN P_ISSUE_ID BIGINT,
	IN P_SUMMARY TEXT,
	IN P_DESCRIPTION TEXT,
	IN P_AUDIT_ID BIGINT,
	IN P_RESOLVE_AT DATE,
	IN P_DUE_DATE DATE,
	IN P_VOTES BIGINT,
	IN P_ORIGINAL_ESTIMATION BIGINT,
	IN P_CUSTOM_START_DATE DATE,
	IN P_STORY_POINT_ESTIMATE BIGINT,
	IN P_PARENT_SUMMARY BIGINT,
	IN P_ISSUE_TYPE BIGINT,
	IN P_PROJECT_ID BIGINT,
	IN P_USER_ASSIGNED BIGINT,
	IN P_USER_CREATOR BIGINT,
	IN P_USER_INFORMATOR BIGINT,
	IN P_SPRINT_ID BIGINT,
	IN P_STATUS BIGINT,
	OUT DATA JSON
) LANGUAGE PLPGSQL AS $$
BEGIN
    UPDATE PUBLIC."ISSUE" i
    SET "SUMMARY" = P_SUMMARY,
        "DESCRIPTION" = P_DESCRIPTION,
        "AUDIT_ID_FK" = P_AUDIT_ID,
        "RESOLVE_AT" = P_RESOLVE_AT,
        "DUE_DATE" = P_DUE_DATE,
        "VOTES" = P_VOTES,
        "ORIGINAL_ESTIMATION" = P_ORIGINAL_ESTIMATION,
        "CUSTOM_START_DATE" = P_CUSTOM_START_DATE,
        "STORY_POINT_ESTIMATE" = P_STORY_POINT_ESTIMATE,
        "PARENT_SUMMARY_FK" = P_PARENT_SUMMARY,
        "ISSUE_TYPE" = P_ISSUE_TYPE,
        "PROJECT_ID_FK" = P_PROJECT_ID,
        "USER_ASSIGNED_FK" = P_USER_ASSIGNED,
        "USER_CREATOR_ISSUE_FK" = P_USER_CREATOR,
        "USER_INFORMATOR_ISSUE_FK" = P_USER_INFORMATOR,
        "SPRINT_ID_FK" = P_SPRINT_ID,
        "STATUS_ISSUE" = P_STATUS
    WHERE "ISSUE_ID" = P_ISSUE_ID
    RETURNING row_to_json(i) INTO DATA;
END;
$$;