CREATE OR REPLACE PROCEDURE PUBLIC."DELETE_SPRINT" (
    IN P_SPRINT_ID BIGINT,
    OUT DATA JSON
)
LANGUAGE PLPGSQL
AS $$
BEGIN
    DELETE FROM PUBLIC."SPRINT" s
    WHERE "SPRINT_ID" = P_SPRINT_ID
    RETURNING to_json(s.*) INTO DATA;
END;
$$;
