CREATE OR REPLACE PROCEDURE PUBLIC."GET_SPRINT"(
    OUT DATA JSON,
    IN P_SPRINT_ID BIGINT DEFAULT NULL,
    IN P_NAME TEXT DEFAULT NULL,
    IN P_DESCRIPTION TEXT DEFAULT NULL,
    IN P_DATE_INIT_START DATE DEFAULT NULL,
    IN P_DATE_INIT_END DATE DEFAULT NULL,
    IN P_DATE_END_START DATE DEFAULT NULL,
    IN P_DATE_END_END DATE DEFAULT NULL,
    IN P_PAGE INT DEFAULT 1,
    IN P_LIMIT INT DEFAULT 10
)
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT *
        FROM PUBLIC."SPRINT" s
        WHERE (P_SPRINT_ID IS NULL OR s."SPRINT_ID" = P_SPRINT_ID)
          AND (P_NAME IS NULL OR s."NAME" ILIKE '%' || P_NAME || '%')
          AND (P_DESCRIPTION IS NULL OR s."DESCRIPTION" ILIKE '%' || P_DESCRIPTION || '%')
          AND (P_DATE_INIT_START IS NULL OR s."DATE_INIT" >= P_DATE_INIT_START)
          AND (P_DATE_INIT_END IS NULL OR s."DATE_INIT" <= P_DATE_INIT_END)
          AND (P_DATE_END_START IS NULL OR s."DATE_END" >= P_DATE_END_START)
          AND (P_DATE_END_END IS NULL OR s."DATE_END" <= P_DATE_END_END)
        ORDER BY s."SPRINT_ID"
        LIMIT P_LIMIT OFFSET (P_PAGE - 1) * P_LIMIT
    ) t;
END;
$$;
