CREATE OR REPLACE PROCEDURE PUBLIC."PATCH_SPRINT" (
    OUT DATA JSON,
    IN P_SPRINT_ID BIGINT,
    IN P_NAME TEXT DEFAULT NULL,
    IN P_DESCRIPTION TEXT DEFAULT NULL,
    IN P_DATE_INIT DATE DEFAULT NULL,
    IN P_DATE_END DATE DEFAULT NULL
)
LANGUAGE PLPGSQL
AS $$
BEGIN
    UPDATE PUBLIC."SPRINT"
    SET "NAME" = COALESCE(P_NAME, "NAME"),
        "DESCRIPTION" = COALESCE(P_DESCRIPTION, "DESCRIPTION"),
        "DATE_INIT" = COALESCE(P_DATE_INIT, "DATE_INIT"),
        "DATE_END" = COALESCE(P_DATE_END, "DATE_END")
    WHERE "SPRINT_ID" = P_SPRINT_ID;

    SELECT to_json(s.*)
    INTO DATA
    FROM PUBLIC."SPRINT" s
    WHERE s."SPRINT_ID" = P_SPRINT_ID;
END;
$$;
