CREATE OR REPLACE PROCEDURE PUBLIC."POST_SPRINT"(
    IN P_NAME TEXT,
    IN P_DESCRIPTION TEXT,
    IN P_DATE_INIT DATE,
    IN P_DATE_END DATE,
    OUT DATA JSON
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_ID BIGINT;
BEGIN
    INSERT INTO PUBLIC."SPRINT" ("NAME", "DESCRIPTION", "DATE_INIT", "DATE_END")
    VALUES (P_NAME, P_DESCRIPTION, P_DATE_INIT, P_DATE_END)
    RETURNING "SPRINT_ID" INTO V_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT s."SPRINT_ID", s."NAME", s."DESCRIPTION",
               s."DATE_INIT", s."DATE_END"
        FROM PUBLIC."SPRINT" s
        WHERE s."SPRINT_ID" = V_ID
    ) t;
END;
$$;