CREATE OR REPLACE PROCEDURE PUBLIC."PUT_SPRINT" (
    IN P_SPRINT_ID BIGINT,
    IN P_NAME TEXT,
    IN P_DESCRIPTION TEXT,
    IN P_DATE_INIT DATE,
    IN P_DATE_END DATE,
    OUT DATA JSON
)
LANGUAGE PLPGSQL
AS $$
BEGIN
    UPDATE PUBLIC."SPRINT"
    SET "NAME" = P_NAME,
        "DESCRIPTION" = P_DESCRIPTION,
        "DATE_INIT" = P_DATE_INIT,
        "DATE_END" = P_DATE_END
    WHERE "SPRINT_ID" = P_SPRINT_ID;
    SELECT to_json(s.*)
    INTO DATA
    FROM PUBLIC."SPRINT" s
    WHERE s."SPRINT_ID" = P_SPRINT_ID;
END;
$$;
