CREATE OR REPLACE PROCEDURE PUBLIC."DELETE_MEMBERSHIP_PLAN"(
    IN P_MEMBERSHIPPLAN_ID BIGINT,
    OUT SUCCESS BOOLEAN
)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM PUBLIC."MEMBERSHIP_PLAN"
    WHERE "MEMBERSHIPPLAN_ID" = P_MEMBERSHIPPLAN_ID;

    SUCCESS := TRUE;
END;
$$;
