CREATE OR REPLACE PROCEDURE PUBLIC."GET_MEMBERSHIP_PLAN"(
    OUT DATA JSON,
    IN P_MEMBERSHIPPLAN_ID BIGINT DEFAULT NULL,
    IN P_NAME TEXT DEFAULT NULL,
    IN P_DESCRIPTION TEXT DEFAULT NULL,
    IN P_AMOUNT NUMERIC DEFAULT NULL,
    IN P_PAGE INT DEFAULT 1,
    IN P_LIMIT INT DEFAULT 10
)
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT
            "MEMBERSHIP_PLAN"."MEMBERSHIPPLAN_ID",
            "MEMBERSHIP_PLAN"."NAME",
            "MEMBERSHIP_PLAN"."DESCRIPTION",
            "MEMBERSHIP_PLAN"."AMOUNT"
        FROM
            PUBLIC."MEMBERSHIP_PLAN"
        WHERE
            (P_MEMBERSHIPPLAN_ID IS NULL OR "MEMBERSHIP_PLAN"."MEMBERSHIPPLAN_ID" = P_MEMBERSHIPPLAN_ID)
            AND (P_NAME IS NULL OR "MEMBERSHIP_PLAN"."NAME" ILIKE '%' || P_NAME || '%')
            AND (P_DESCRIPTION IS NULL OR "MEMBERSHIP_PLAN"."DESCRIPTION" ILIKE '%' || P_DESCRIPTION || '%')
            AND (P_AMOUNT IS NULL OR "MEMBERSHIP_PLAN"."AMOUNT" = P_AMOUNT)
        ORDER BY "MEMBERSHIP_PLAN"."MEMBERSHIPPLAN_ID"
        LIMIT P_LIMIT
        OFFSET (P_PAGE - 1) * P_LIMIT
    ) t;
END;
$$;
