CREATE OR REPLACE PROCEDURE PUBLIC."PATCH_MEMBERSHIP_PLAN"(
    IN P_MEMBERSHIPPLAN_ID BIGINT,
    IN P_NAME TEXT DEFAULT NULL,
    IN P_DESCRIPTION TEXT DEFAULT NULL,
    IN P_AMOUNT NUMERIC DEFAULT NULL,
    OUT DATA JSON
)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE PUBLIC."MEMBERSHIP_PLAN"
    SET "NAME" = COALESCE(P_NAME, "NAME"),
        "DESCRIPTION" = COALESCE(P_DESCRIPTION, "DESCRIPTION"),
        "AMOUNT" = COALESCE(P_AMOUNT, "AMOUNT")
    WHERE "MEMBERSHIPPLAN_ID" = P_MEMBERSHIPPLAN_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT
            "MEMBERSHIP_PLAN"."MEMBERSHIPPLAN_ID",
            "MEMBERSHIP_PLAN"."NAME",
            "MEMBERSHIP_PLAN"."DESCRIPTION",
            "MEMBERSHIP_PLAN"."AMOUNT"
        FROM PUBLIC."MEMBERSHIP_PLAN"
        WHERE "MEMBERSHIPPLAN_ID" = P_MEMBERSHIPPLAN_ID
    ) t;
END;
$$;
