CREATE OR REPLACE PROCEDURE PUBLIC."POST_MEMBERSHIP_PLAN"(
    IN P_NAME TEXT,
    IN P_DESCRIPTION TEXT,
    IN P_AMOUNT NUMERIC,
    OUT DATA JSON
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_ID BIGINT;
BEGIN
    INSERT INTO PUBLIC."MEMBERSHIP_PLAN" ("NAME", "DESCRIPTION", "AMOUNT")
    VALUES (P_NAME, P_DESCRIPTION, P_AMOUNT)
    RETURNING "MEMBERSHIPPLAN_ID" INTO V_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT
            "MEMBERSHIP_PLAN"."MEMBERSHIPPLAN_ID",
            "MEMBERSHIP_PLAN"."NAME",
            "MEMBERSHIP_PLAN"."DESCRIPTION",
            "MEMBERSHIP_PLAN"."AMOUNT"
        FROM PUBLIC."MEMBERSHIP_PLAN"
        WHERE "MEMBERSHIPPLAN_ID" = V_ID
    ) t;
END;
$$;
