CREATE OR REPLACE PROCEDURE PUBLIC."PUT_MEMBERSHIP_PLAN"(
    IN P_MEMBERSHIPPLAN_ID BIGINT,
    IN P_NAME TEXT,
    IN P_DESCRIPTION TEXT,
    IN P_AMOUNT NUMERIC,
    OUT DATA JSON
)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE PUBLIC."MEMBERSHIP_PLAN"
    SET "NAME" = P_NAME,
        "DESCRIPTION" = P_DESCRIPTION,
        "AMOUNT" = P_AMOUNT
    WHERE "MEMBERSHIPPLAN_ID" = P_MEMBERSHIPPLAN_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT
            "MEMBERSHIP_PLAN"."MEMBERSHIPPLAN_ID",
            "MEMBERSHIP_PLAN"."NAME",
            "MEMBERSHIP_PLAN"."DESCRIPTION",
            "MEMBERSHIP_PLAN"."AMOUNT"
        FROM PUBLIC."MEMBERSHIP_PLAN"
        WHERE "MEMBERSHIPPLAN_ID" = P_MEMBERSHIPPLAN_ID
    ) t;
END;
$$;
