CREATE OR REPLACE PROCEDURE PUBLIC."DELETE_RECOVER_PASSWORD"(
    IN P_RECOVER_PASSWORD_ID BIGINT,
    OUT DATA JSON
)
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT "RECOVER_PASSWORD_ID", "USER_ID", "OTP", "IS_USED", "EXPIRY_DATE"
        FROM PUBLIC."RECOVER_PASSWORD"
        WHERE "RECOVER_PASSWORD_ID" = P_RECOVER_PASSWORD_ID
    ) t;

    DELETE FROM PUBLIC."RECOVER_PASSWORD"
    WHERE "RECOVER_PASSWORD_ID" = P_RECOVER_PASSWORD_ID;
END;
$$;
