CREATE OR REPLACE PROCEDURE PUBLIC."GET_RECOVER_PASSWORD"(
    OUT DATA JSON,
    IN P_RECOVER_PASSWORD_ID BIGINT DEFAULT NULL,
    IN P_USER_ID BIGINT DEFAULT NULL,
    IN P_OTP TEXT DEFAULT NULL,
    IN P_IS_USED BIGINT DEFAULT NULL,
    IN P_EXPIRY_DATE DATE DEFAULT NULL,
    IN P_PAGE INT DEFAULT 1,
    IN P_LIMIT INT DEFAULT 10
)
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT "RECOVER_PASSWORD_ID", "USER_ID", "OTP", "IS_USED", "EXPIRY_DATE"
        FROM PUBLIC."RECOVER_PASSWORD"
        WHERE (P_RECOVER_PASSWORD_ID IS NULL OR "RECOVER_PASSWORD_ID" = P_RECOVER_PASSWORD_ID)
          AND (P_USER_ID IS NULL OR "USER_ID" = P_USER_ID)
          AND (P_OTP IS NULL OR "OTP" = P_OTP)
          AND (P_IS_USED IS NULL OR "IS_USED" = P_IS_USED)
          AND (P_EXPIRY_DATE IS NULL OR "EXPIRY_DATE" = P_EXPIRY_DATE)
        ORDER BY "RECOVER_PASSWORD_ID"
        LIMIT P_LIMIT OFFSET (P_PAGE - 1) * P_LIMIT
    ) t;
END;
$$;
