CREATE OR REPLACE PROCEDURE PUBLIC."PATCH_RECOVER_PASSWORD" (
	OUT DATA JSON,
	IN P_RECOVER_PASSWORD_ID BIGINT,
	IN P_USER_ID BIGINT DEFAULT NULL,
	IN P_OTP TEXT DEFAULT NULL,
	IN P_IS_USED BIGINT DEFAULT NULL,
	IN P_EXPIRY_DATE DATE DEFAULT NULL
) LANGUAGE PLPGSQL AS $$
BEGIN
    UPDATE PUBLIC."RECOVER_PASSWORD"
    SET "USER_ID" = COALESCE(P_USER_ID, "USER_ID"),
        "OTP" = COALESCE(P_OTP, "OTP"),
        "IS_USED" = COALESCE(P_IS_USED, "IS_USED"),
        "EXPIRY_DATE" = COALESCE(P_EXPIRY_DATE, "EXPIRY_DATE")
    WHERE "RECOVER_PASSWORD_ID" = P_RECOVER_PASSWORD_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT "RECOVER_PASSWORD_ID", "USER_ID", "OTP", "IS_USED", "EXPIRY_DATE"
        FROM PUBLIC."RECOVER_PASSWORD"
        WHERE "RECOVER_PASSWORD_ID" = P_RECOVER_PASSWORD_ID
    ) t;
END;
$$;