CREATE OR REPLACE PROCEDURE PUBLIC."POST_RECOVER_PASSWORD"(
    IN P_USER_ID BIGINT,
    IN P_OTP TEXT,
    IN P_IS_USED BIGINT,
    IN P_EXPIRY_DATE DATE,
    OUT DATA JSON
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_ID BIGINT;
BEGIN
    INSERT INTO PUBLIC."RECOVER_PASSWORD" ("USER_ID", "OTP", "IS_USED", "EXPIRY_DATE")
    VALUES (P_USER_ID, P_OTP, P_IS_USED, P_EXPIRY_DATE)
    RETURNING "RECOVER_PASSWORD_ID" INTO V_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT "RECOVER_PASSWORD_ID", "USER_ID", "OTP", "IS_USED", "EXPIRY_DATE"
        FROM PUBLIC."RECOVER_PASSWORD"
        WHERE "RECOVER_PASSWORD_ID" = V_ID
    ) t;
END;
$$;
