CREATE OR REPLACE PROCEDURE PUBLIC."PUT_RECOVER_PASSWORD"(
    IN P_RECOVER_PASSWORD_ID BIGINT,
    IN P_USER_ID BIGINT,
    IN P_OTP TEXT,
    IN P_IS_USED BIGINT,
    IN P_EXPIRY_DATE DATE,
    OUT DATA JSON
)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE PUBLIC."RECOVER_PASSWORD"
    SET "USER_ID" = P_USER_ID,
        "OTP" = P_OTP,
        "IS_USED" = P_IS_USED,
        "EXPIRY_DATE" = P_EXPIRY_DATE
    WHERE "RECOVER_PASSWORD_ID" = P_RECOVER_PASSWORD_ID;

    SELECT json_agg(t)
    INTO DATA
    FROM (
        SELECT "RECOVER_PASSWORD_ID", "USER_ID", "OTP", "IS_USED", "EXPIRY_DATE"
        FROM PUBLIC."RECOVER_PASSWORD"
        WHERE "RECOVER_PASSWORD_ID" = P_RECOVER_PASSWORD_ID
    ) t;
END;
$$;
